### PR TITLE
Fix Regene Bugs

### LINKED ISSUE #629: CUser::Regene() bugs
CUser::Regene() (used on respawn) is a bit outdated and buggy.
Ignoring the functionality that doesn't exist, the 2 main problems with it right now are that:
1. The positioning logic is outdated and can fall through to not even finding a position (e.g. when dying in Moradon).
2. Doesn't restore HP. This is apparently just commented out; it shouldn't be.

### PR DESCRIPTION
**Pull request by stefannikolei**
Fixes #629

I hope I extracted the correct code from the posted reference.

Could not test it atm, because no windows machine to run the client on.

### CODE REVIEW

File: Server/Ebenezer/User.cpp [hunk 1]
```diff
@@ -2412,6 +2412,12 @@ void CUser::Regene(char* pBuf, int magicid)
 				}
 				else return;
 			}
+			int16_t spawnX = 0, spawnZ = 0;	// The point where you will be warped to.
```
Comment (twostars) [inline Server/Ebenezer/User.cpp]: This is overriding all of the previous blocks. I assume this was intended to be in an `else` block following them.

**Review by twostars — CHANGES_REQUESTED** [review]

File: Server/Ebenezer/User.cpp (hunk 1 above)
Comment (stefannikolei) [reply Server/Ebenezer/User.cpp]: Yep. Seems I missed the else in front of the return.

**Review by twostars — APPROVED** [review]
